version: '3.8'

x-airflow-common:
  &airflow-common
  build:
    context: ./airflow
    dockerfile: Dockerfile
  environment:
    &airflow-common-env
    AIRFLOW__CORE__EXECUTOR: CeleryExecutor
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: ${AIRFLOW__CORE__SQL_ALCHEMY_CONN}
    AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://airflow:airflow@airflow-db/airflow
    AIRFLOW__CELERY__BROKER_URL: redis://:@redis:6379/0
    AIRFLOW__CORE__FERNET_KEY: ''
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
    AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    AIRFLOW__API__AUTH_BACKENDS: 'airflow.api.auth.backend.basic_auth,airflow.api.auth.backend.session'
    AIRFLOW__SCHEDULER__ENABLE_HEALTH_CHECK: 'true'
    AIRFLOW__WEBSERVER__BASE_URL: http://airflow-webserver:8080
    AIRFLOW_CONN_PROCESSED_FILES_DB: ${AIRFLOW_CONN_PROCESSED_FILES_DB}
  env_file:
    - .env
  volumes:
    - ./airflow/dags:/opt/airflow/dags
    - ./airflow/logs:/opt/airflow/logs
    - ./airflow/config:/opt/airflow/config
    - ./airflow/plugins:/opt/airflow/plugins
    - ./airflow/data:/opt/airflow/data
    - ./airflow/great_expectations:/opt/airflow/great_expectations
  user: "${AIRFLOW_UID:-50000}:0"
  depends_on:
    redis:
      condition: service_healthy
    airflow-db:
      condition: service_healthy

services:
  db:
    image: postgres:13
    container_name: fastapi_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: piggy
      POSTGRES_DB: employee_app_db
    ports:
      - "5432:5432"
    volumes:
      - fastapi_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d employee_app_db"]
      interval: 5s
      retries: 5
      timeout: 5s
    networks:
      - app-network
      - shared-network

  airflow-db:
    image: postgres:13
    container_name: airflow_db
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5433:5432"
    volumes:
      - airflow_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow -d airflow"]
      interval: 5s
      retries: 5
      timeout: 5s
    networks:
      - airflow-network
      - shared-network

  redis:
    image: redis:7.2-bookworm
    container_name: airflow_redis
    expose:
      - 6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 30s
      retries: 50
      start_period: 30s
    restart: always
    networks:
      - airflow-network
      - shared-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: project
    ports:
      - "5050:80"
    networks:
      - shared-network
    depends_on:
      - db
      - airflow-db

  fastapi:
    build:
      context: ./FastApi
    container_name: fastapi_app
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./FastApi:/app
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network
      - shared-network

  webapp:
    build:
      context: ./Webapp
    ports:
      - "8501:8501"
    env_file:
      - .env
    depends_on:
      - fastapi
    networks:
      - app-network
      - shared-network

  airflow-webserver:
    <<: *airflow-common
    container_name: airflow_webserver
    command: webserver
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: always
    depends_on:
      - airflow-init
    networks:
      - airflow-network
      - shared-network

  airflow-scheduler:
    <<: *airflow-common
    container_name: airflow_scheduler
    command: scheduler
    restart: always
    depends_on:
      - airflow-init
    networks:
      - airflow-network
      - shared-network

  airflow-worker:
    <<: *airflow-common
    container_name: airflow_worker
    command: celery worker
    restart: always
    depends_on:
      - airflow-init
    networks:
      - airflow-network
      - shared-network

  airflow-triggerer:
    <<: *airflow-common
    container_name: airflow_triggerer
    command: triggerer
    restart: always
    depends_on:
      - airflow-init
    networks:
      - airflow-network
      - shared-network

  airflow-init:
    <<: *airflow-common
    container_name: airflow_init
    entrypoint: /bin/bash
    command:
      - -c
      - |
        mkdir -p /sources/logs /sources/dags /sources/plugins
        chown -R "${AIRFLOW_UID}:0" /sources/{logs,dags,plugins}
        exec /entrypoint airflow version
    environment:
      _AIRFLOW_DB_MIGRATE: 'true'
      _AIRFLOW_WWW_USER_CREATE: 'true'
      _AIRFLOW_WWW_USER_USERNAME: ${_AIRFLOW_WWW_USER_USERNAME:-airflow}
      _AIRFLOW_WWW_USER_PASSWORD: ${_AIRFLOW_WWW_USER_PASSWORD:-airflow}
    user: "0:0"
    volumes:
      - ${AIRFLOW_PROJ_DIR:-./airflow}:/sources
    networks:
      - airflow-network
      - shared-network

  flower:
    <<: *airflow-common
    container_name: airflow_flower
    command: celery flower
    ports:
      - "5555:5555"
    restart: always
    depends_on:
      - airflow-init
    networks:
      - airflow-network
      - shared-network

  ge-docs-server:
    image: nginx:alpine
    container_name: ge_docs_server
    ports:
      - "8085:80"
    volumes:
      - ./airflow/great_expectations/uncommitted/data_docs/local_site:/usr/share/nginx/html:ro
    networks:
      - shared-network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=dsp
      - GF_SECURITY_ADMIN_PASSWORD=project
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - shared-network
    depends_on:
      - db

volumes:
  fastapi_postgres_data:
  airflow_postgres_data:
  grafana-storage:

networks:
  app-network:
    driver: bridge
  airflow-network:
    driver: bridge
  shared-network:
    driver: bridge
