# grafana/provisioning/datasources/datasource.yml
apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    access: proxy
    url: postgres:5432
    database: mlops_db
    user: mlops_user
    secureJsonData:
    password: mlops_pass
    isDefault: true
    editable: true
    jsonData:
      sslmode: disable
