version: '3.8'

services:

  db:
    image: postgres:13
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: youruser
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: employee_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: ./docker/fastapi
    container_name: fastapi_backend
    restart: always
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://youruser:yourpassword@db:5432/employee_db

  frontend:
    build: ./docker/streamlit
    container_name: streamlit_frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "8501:8501"

  airflow:
    build: ./docker/airflow
    container_name: airflow_server
    restart: always
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://youruser:yourpassword@db:5432/airflow_db
      AIRFLOW__WEBSERVER__RBAC: "True"

volumes:
  postgres_data:
