version: "3.8"

services:
  airflow:
    build: ./airflow
    container_name: airflow_scheduler
    restart: always
    depends_on:
      - backend
      - db
    ports:
      - "8080:8080"
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql://postgres:password@db:5432/employee_performance
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
